package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.facebook.stetho.server.http.HttpStatus;
import com.facebook.stetho.websocket.CloseCodes;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import org.rbmain.messenger.MessagesController;

/* compiled from: com.google.android.gms:play-services-measurement-impl@@18.0.2 */
/* loaded from: classes3.dex */
public final class zzdw {
    public static final zzdv<Long> zzA;
    public static final zzdv<Integer> zzB;
    public static final zzdv<Long> zzC;
    public static final zzdv<Integer> zzD;
    public static final zzdv<Integer> zzE;
    public static final zzdv<Integer> zzF;
    public static final zzdv<Integer> zzG;
    public static final zzdv<Integer> zzH;
    public static final zzdv<Long> zzI;
    public static final zzdv<Boolean> zzJ;
    public static final zzdv<String> zzK;
    public static final zzdv<Long> zzL;
    public static final zzdv<Integer> zzM;
    public static final zzdv<Double> zzN;
    public static final zzdv<Integer> zzO;
    public static final zzdv<Integer> zzP;
    public static final zzdv<Long> zzQ;
    public static final zzdv<Boolean> zzR;
    public static final zzdv<Boolean> zzS;
    public static final zzdv<Boolean> zzT;
    public static final zzdv<Boolean> zzU;
    public static final zzdv<Boolean> zzV;
    public static final zzdv<Boolean> zzW;
    public static final zzdv<Boolean> zzX;
    public static final zzdv<Boolean> zzY;
    public static final zzdv<Boolean> zzZ;
    public static final zzdv<Long> zza;
    public static final zzdv<Boolean> zzaA;
    public static final zzdv<Boolean> zzaB;
    private static final List<zzdv<?>> zzaC = Collections.synchronizedList(new ArrayList());
    public static final zzdv<Boolean> zzaa;
    public static final zzdv<Boolean> zzab;
    public static final zzdv<Boolean> zzac;
    public static final zzdv<Boolean> zzad;
    public static final zzdv<Boolean> zzae;
    public static final zzdv<Boolean> zzaf;
    public static final zzdv<Boolean> zzag;
    public static final zzdv<Boolean> zzah;
    public static final zzdv<Boolean> zzai;
    public static final zzdv<Boolean> zzaj;
    public static final zzdv<Boolean> zzak;
    public static final zzdv<Boolean> zzal;
    public static final zzdv<Boolean> zzam;
    public static final zzdv<Boolean> zzan;
    public static final zzdv<Boolean> zzao;
    public static final zzdv<Boolean> zzap;
    public static final zzdv<Boolean> zzaq;
    public static final zzdv<Boolean> zzar;
    public static final zzdv<Boolean> zzas;
    public static final zzdv<Boolean> zzat;
    public static final zzdv<Boolean> zzav;
    public static final zzdv<Boolean> zzaw;
    public static final zzdv<Boolean> zzax;
    public static final zzdv<Boolean> zzay;
    public static final zzdv<Integer> zzaz;
    public static final zzdv<Long> zzb;
    public static final zzdv<Long> zzc;
    public static final zzdv<String> zzd;
    public static final zzdv<String> zze;
    public static final zzdv<Integer> zzf;
    public static final zzdv<Integer> zzg;
    public static final zzdv<Integer> zzh;
    public static final zzdv<Integer> zzi;
    public static final zzdv<Integer> zzj;
    public static final zzdv<Integer> zzk;
    public static final zzdv<Integer> zzl;
    public static final zzdv<Integer> zzm;
    public static final zzdv<Integer> zzn;
    public static final zzdv<Integer> zzo;
    public static final zzdv<String> zzp;
    public static final zzdv<Long> zzq;
    public static final zzdv<Long> zzr;
    public static final zzdv<Long> zzs;
    public static final zzdv<Long> zzt;
    public static final zzdv<Long> zzu;
    public static final zzdv<Long> zzv;
    public static final zzdv<Long> zzw;
    public static final zzdv<Long> zzx;
    public static final zzdv<Long> zzy;
    public static final zzdv<Long> zzz;

    static {
        Collections.synchronizedSet(new HashSet());
        zza = zzb("measurement.ad_id_cache_time", 10000L, 10000L, zzau.zza);
        zzb = zzb("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzbf.zza);
        zzc = zzb("measurement.config.cache_time", 86400000L, 3600000L, zzbq.zza);
        zzd = zzb("measurement.config.url_scheme", "https", "https", zzcb.zza);
        zze = zzb("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcm.zza);
        zzf = zzb("measurement.upload.max_bundles", 100, 100, zzcx.zza);
        Integer numValueOf = Integer.valueOf(MessagesController.UPDATE_MASK_CHECK);
        zzg = zzb("measurement.upload.max_batch_size", numValueOf, numValueOf, zzdi.zza);
        zzh = zzb("measurement.upload.max_bundle_size", numValueOf, numValueOf, zzdp.zza);
        Integer numValueOf2 = Integer.valueOf(CloseCodes.NORMAL_CLOSURE);
        zzi = zzb("measurement.upload.max_events_per_bundle", numValueOf2, numValueOf2, zzdq.zza);
        zzj = zzb("measurement.upload.max_events_per_day", 100000, 100000, zzdr.zza);
        zzk = zzb("measurement.upload.max_error_events_per_day", numValueOf2, numValueOf2, zzav.zza);
        zzl = zzb("measurement.upload.max_public_events_per_day", 50000, 50000, zzaw.zza);
        zzm = zzb("measurement.upload.max_conversions_per_day", 10000, 10000, zzax.zza);
        zzn = zzb("measurement.upload.max_realtime_events_per_day", 10, 10, zzay.zza);
        zzo = zzb("measurement.store.max_stored_events_per_app", 100000, 100000, zzaz.zza);
        zzp = zzb("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzba.zza);
        zzq = zzb("measurement.upload.backoff_period", 43200000L, 43200000L, zzbb.zza);
        zzr = zzb("measurement.upload.window_interval", 3600000L, 3600000L, zzbc.zza);
        zzs = zzb("measurement.upload.interval", 3600000L, 3600000L, zzbd.zza);
        zzt = zzb("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbe.zza);
        zzu = zzb("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbg.zza);
        zzv = zzb("measurement.upload.minimum_delay", 500L, 500L, zzbh.zza);
        zzw = zzb("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbi.zza);
        zzx = zzb("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbj.zza);
        zzy = zzb("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbk.zza);
        zzz = zzb("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbl.zza);
        zzA = zzb("measurement.upload.retry_time", 1800000L, 1800000L, zzbm.zza);
        zzB = zzb("measurement.upload.retry_count", 6, 6, zzbn.zza);
        zzC = zzb("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbo.zza);
        zzD = zzb("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbp.zza);
        zzE = zzb("measurement.audience.filter_result_max_count", 200, 200, zzbr.zza);
        zzF = zzb("measurement.upload.max_public_user_properties", 25, 25, null);
        Integer numValueOf3 = Integer.valueOf(HttpStatus.HTTP_INTERNAL_SERVER_ERROR);
        zzG = zzb("measurement.upload.max_event_name_cardinality", numValueOf3, numValueOf3, null);
        zzH = zzb("measurement.upload.max_public_event_params", 25, 25, null);
        zzI = zzb("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbs.zza);
        Boolean bool = Boolean.FALSE;
        zzJ = zzb("measurement.test.boolean_flag", bool, bool, zzbt.zza);
        zzK = zzb("measurement.test.string_flag", "---", "---", zzbu.zza);
        zzL = zzb("measurement.test.long_flag", -1L, -1L, zzbv.zza);
        zzM = zzb("measurement.test.int_flag", -2, -2, zzbw.zza);
        Double dValueOf = Double.valueOf(-3.0d);
        zzN = zzb("measurement.test.double_flag", dValueOf, dValueOf, zzbx.zza);
        zzO = zzb("measurement.experiment.max_ids", 50, 50, zzby.zza);
        zzP = zzb("measurement.max_bundles_per_iteration", 100, 100, zzbz.zza);
        zzQ = zzb("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzca.zza);
        zzR = zzb("measurement.validation.internal_limits_internal_event_params", bool, bool, zzcc.zza);
        Boolean bool2 = Boolean.TRUE;
        zzS = zzb("measurement.collection.firebase_global_collection_flag_enabled", bool2, bool2, zzcd.zza);
        zzT = zzb("measurement.collection.redundant_engagement_removal_enabled", bool, bool, zzce.zza);
        zzU = zzb("measurement.collection.log_event_and_bundle_v2", bool2, bool2, zzcf.zza);
        zzV = zzb("measurement.quality.checksum", bool, bool, null);
        zzW = zzb("measurement.sdk.dynamite.allow_remote_dynamite3", bool2, bool2, zzcg.zza);
        zzX = zzb("measurement.sdk.collection.validate_param_names_alphabetical", bool2, bool2, zzch.zza);
        zzY = zzb("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, zzci.zza);
        zzZ = zzb("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, zzcj.zza);
        zzaa = zzb("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, zzck.zza);
        zzab = zzb("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, zzcl.zza);
        zzac = zzb("measurement.sdk.collection.last_deep_link_referrer2", bool2, bool2, zzcn.zza);
        zzad = zzb("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, zzco.zza);
        zzae = zzb("measurement.sdk.collection.last_gclid_from_referrer2", bool, bool, zzcp.zza);
        zzaf = zzb("measurement.sdk.collection.enable_extend_user_property_size", bool2, bool2, zzcq.zza);
        zzag = zzb("measurement.upload.file_lock_state_check", bool, bool, zzcr.zza);
        zzah = zzb("measurement.ga.ga_app_id", bool, bool, zzcs.zza);
        zzai = zzb("measurement.lifecycle.app_in_background_parameter", bool, bool, zzct.zza);
        zzaj = zzb("measurement.integration.disable_firebase_instance_id", bool, bool, zzcu.zza);
        zzak = zzb("measurement.lifecycle.app_backgrounded_engagement", bool, bool, zzcv.zza);
        zzal = zzb("measurement.collection.service.update_with_analytics_fix", bool, bool, zzcw.zza);
        zzam = zzb("measurement.service.use_appinfo_modified", bool, bool, zzcy.zza);
        zzan = zzb("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, zzcz.zza);
        zzao = zzb("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, zzda.zza);
        zzap = zzb("measurement.scheduler.task_thread.cleanup_on_exit", bool, bool, zzdb.zza);
        zzaq = zzb("measurement.upload.file_truncate_fix", bool, bool, zzdc.zza);
        zzar = zzb("measurement.sdk.referrer.delayed_install_referrer_api", bool, bool, zzdd.zza);
        zzas = zzb("measurement.sdk.screen.disabling_automatic_reporting", bool2, bool2, zzde.zza);
        zzat = zzb("measurement.sdk.screen.manual_screen_view_logging", bool2, bool2, zzdf.zza);
        zzb("measurement.collection.synthetic_data_mitigation", bool, bool, zzdg.zza);
        zzav = zzb("measurement.androidId.delete_feature", bool2, bool2, zzdh.zza);
        zzaw = zzb("measurement.client.consent_state_v1", bool2, bool2, zzdj.zza);
        zzax = zzb("measurement.client.3p_consent_state_v1", bool2, bool2, zzdk.zza);
        zzay = zzb("measurement.service.consent_state_v1_W36", bool2, bool2, zzdl.zza);
        zzaz = zzb("measurement.service.storage_consent_support_version", 203590, 203590, zzdm.zza);
        zzaA = zzb("measurement.service.directly_maybe_log_error_events", bool, bool, zzdn.zza);
        zzaB = zzb("measurement.client.safer_resources", bool2, bool2, zzdo.zza);
    }

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzen zzenVarZza = com.google.android.gms.internal.measurement.zzen.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzex.zza("com.google.android.gms.measurement"));
        return zzenVarZza == null ? Collections.emptyMap() : zzenVarZza.zzb();
    }

    static <V> zzdv<V> zzb(String str, V v, V v2, zzdt<V> zzdtVar) {
        zzdv<V> zzdvVar = new zzdv<>(str, v, v2, zzdtVar, null);
        zzaC.add(zzdvVar);
        return zzdvVar;
    }
}
