package org.bouncycastle.asn1.pkcs;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* loaded from: classes4.dex */
public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier bagtypes;
    public static final ASN1ObjectIdentifier certTypes;
    public static final ASN1ObjectIdentifier crlTypes;
    public static final ASN1ObjectIdentifier digestAlgorithm;
    public static final ASN1ObjectIdentifier encryptionAlgorithm;
    public static final ASN1ObjectIdentifier id_aa;
    public static final ASN1ObjectIdentifier id_aa_ets_commitmentType;
    public static final ASN1ObjectIdentifier id_aa_ets_otherSigCert;
    public static final ASN1ObjectIdentifier id_aa_ets_sigPolicyId;
    public static final ASN1ObjectIdentifier id_aa_ets_signerLocation;
    public static final ASN1ObjectIdentifier id_alg;
    public static final ASN1ObjectIdentifier id_alg_hss_lms_hashsig;
    public static final ASN1ObjectIdentifier id_ct;
    public static final ASN1ObjectIdentifier id_cti;
    public static final ASN1ObjectIdentifier id_smime;
    public static final ASN1ObjectIdentifier pkcs_1;
    public static final ASN1ObjectIdentifier pkcs_12;
    public static final ASN1ObjectIdentifier pkcs_12PbeIds;
    public static final ASN1ObjectIdentifier pkcs_3;
    public static final ASN1ObjectIdentifier pkcs_5;
    public static final ASN1ObjectIdentifier pkcs_9;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        pkcs_1 = aSN1ObjectIdentifier;
        aSN1ObjectIdentifier.branch("1");
        aSN1ObjectIdentifier.branch("2");
        aSN1ObjectIdentifier.branch("3");
        aSN1ObjectIdentifier.branch("4");
        aSN1ObjectIdentifier.branch("5");
        aSN1ObjectIdentifier.branch("6");
        aSN1ObjectIdentifier.branch("7");
        aSN1ObjectIdentifier.branch("8");
        aSN1ObjectIdentifier.branch("9");
        aSN1ObjectIdentifier.branch("10");
        aSN1ObjectIdentifier.branch("11");
        aSN1ObjectIdentifier.branch("12");
        aSN1ObjectIdentifier.branch("13");
        aSN1ObjectIdentifier.branch("14");
        aSN1ObjectIdentifier.branch("15");
        aSN1ObjectIdentifier.branch("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        pkcs_3 = aSN1ObjectIdentifier2;
        aSN1ObjectIdentifier2.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        pkcs_5 = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.branch("1");
        aSN1ObjectIdentifier3.branch("4");
        aSN1ObjectIdentifier3.branch("3");
        aSN1ObjectIdentifier3.branch("6");
        aSN1ObjectIdentifier3.branch("10");
        aSN1ObjectIdentifier3.branch("11");
        aSN1ObjectIdentifier3.branch("13");
        aSN1ObjectIdentifier3.branch("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        encryptionAlgorithm = aSN1ObjectIdentifier4;
        aSN1ObjectIdentifier4.branch("7");
        aSN1ObjectIdentifier4.branch("2");
        aSN1ObjectIdentifier4.branch("4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        digestAlgorithm = aSN1ObjectIdentifier5;
        aSN1ObjectIdentifier5.branch("2");
        aSN1ObjectIdentifier5.branch("4");
        aSN1ObjectIdentifier5.branch("5");
        aSN1ObjectIdentifier5.branch("7").intern();
        aSN1ObjectIdentifier5.branch("8").intern();
        aSN1ObjectIdentifier5.branch("9").intern();
        aSN1ObjectIdentifier5.branch("10").intern();
        aSN1ObjectIdentifier5.branch("11").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").intern();
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        pkcs_9 = aSN1ObjectIdentifier6;
        aSN1ObjectIdentifier6.branch("1").intern();
        aSN1ObjectIdentifier6.branch("2").intern();
        aSN1ObjectIdentifier6.branch("3").intern();
        aSN1ObjectIdentifier6.branch("4").intern();
        aSN1ObjectIdentifier6.branch("5").intern();
        aSN1ObjectIdentifier6.branch("6").intern();
        aSN1ObjectIdentifier6.branch("7").intern();
        aSN1ObjectIdentifier6.branch("8").intern();
        aSN1ObjectIdentifier6.branch("9").intern();
        aSN1ObjectIdentifier6.branch("13").intern();
        aSN1ObjectIdentifier6.branch("14").intern();
        aSN1ObjectIdentifier6.branch("15").intern();
        ASN1ObjectIdentifier aSN1ObjectIdentifierIntern = aSN1ObjectIdentifier6.branch("16").intern();
        id_smime = aSN1ObjectIdentifierIntern;
        aSN1ObjectIdentifier6.branch("20").intern();
        aSN1ObjectIdentifier6.branch("21").intern();
        aSN1ObjectIdentifier6.branch("22.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier6.branch("22");
        certTypes = aSN1ObjectIdentifierBranch;
        aSN1ObjectIdentifierBranch.branch("1").intern();
        aSN1ObjectIdentifierBranch.branch("2").intern();
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = aSN1ObjectIdentifier6.branch("23");
        crlTypes = aSN1ObjectIdentifierBranch2;
        aSN1ObjectIdentifierBranch2.branch("1").intern();
        aSN1ObjectIdentifier6.branch("52").intern();
        aSN1ObjectIdentifier6.branch("15.1");
        aSN1ObjectIdentifier6.branch("15.2");
        aSN1ObjectIdentifier6.branch("15.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        id_ct = aSN1ObjectIdentifier7;
        aSN1ObjectIdentifier7.branch("2");
        aSN1ObjectIdentifier7.branch("4");
        aSN1ObjectIdentifier7.branch("9");
        aSN1ObjectIdentifier7.branch("23");
        aSN1ObjectIdentifier7.branch("31");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = aSN1ObjectIdentifierIntern.branch("3");
        id_alg = aSN1ObjectIdentifierBranch3;
        aSN1ObjectIdentifierBranch3.branch("9");
        aSN1ObjectIdentifierBranch3.branch("14");
        id_alg_hss_lms_hashsig = aSN1ObjectIdentifierBranch3.branch("17");
        aSN1ObjectIdentifierBranch3.branch("18");
        aSN1ObjectIdentifierBranch3.branch("28");
        aSN1ObjectIdentifierBranch3.branch("29");
        aSN1ObjectIdentifierBranch3.branch("30");
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        id_cti = aSN1ObjectIdentifier8;
        aSN1ObjectIdentifier8.branch("1");
        aSN1ObjectIdentifier8.branch("2");
        aSN1ObjectIdentifier8.branch("3");
        aSN1ObjectIdentifier8.branch("4");
        aSN1ObjectIdentifier8.branch("5");
        aSN1ObjectIdentifier8.branch("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        id_aa = aSN1ObjectIdentifier9;
        aSN1ObjectIdentifier9.branch("1");
        aSN1ObjectIdentifier9.branch("4");
        aSN1ObjectIdentifier9.branch("5");
        aSN1ObjectIdentifier9.branch("10");
        aSN1ObjectIdentifier9.branch("11");
        aSN1ObjectIdentifier9.branch("12");
        aSN1ObjectIdentifier9.branch("47");
        aSN1ObjectIdentifier9.branch("7");
        aSN1ObjectIdentifier9.branch("14");
        id_aa_ets_sigPolicyId = aSN1ObjectIdentifier9.branch("15");
        id_aa_ets_commitmentType = aSN1ObjectIdentifier9.branch("16");
        id_aa_ets_signerLocation = aSN1ObjectIdentifier9.branch("17");
        aSN1ObjectIdentifier9.branch("18");
        id_aa_ets_otherSigCert = aSN1ObjectIdentifier9.branch("19");
        aSN1ObjectIdentifier9.branch("20");
        aSN1ObjectIdentifier9.branch("21");
        aSN1ObjectIdentifier9.branch("22");
        aSN1ObjectIdentifier9.branch("23");
        aSN1ObjectIdentifier9.branch("24");
        aSN1ObjectIdentifier9.branch("25");
        aSN1ObjectIdentifier9.branch("26");
        aSN1ObjectIdentifier9.branch("27");
        aSN1ObjectIdentifier9.branch("37");
        aSN1ObjectIdentifier9.branch("38");
        aSN1ObjectIdentifier9.branch("54");
        aSN1ObjectIdentifier9.branch("43");
        aSN1ObjectIdentifier9.branch("40");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        pkcs_12 = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch4 = aSN1ObjectIdentifier10.branch("10.1");
        bagtypes = aSN1ObjectIdentifierBranch4;
        aSN1ObjectIdentifierBranch4.branch("1");
        aSN1ObjectIdentifierBranch4.branch("2");
        aSN1ObjectIdentifierBranch4.branch("3");
        aSN1ObjectIdentifierBranch4.branch("4");
        aSN1ObjectIdentifierBranch4.branch("5");
        aSN1ObjectIdentifierBranch4.branch("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch5 = aSN1ObjectIdentifier10.branch("1");
        pkcs_12PbeIds = aSN1ObjectIdentifierBranch5;
        aSN1ObjectIdentifierBranch5.branch("1");
        aSN1ObjectIdentifierBranch5.branch("2");
        aSN1ObjectIdentifierBranch5.branch("3");
        aSN1ObjectIdentifierBranch5.branch("4");
        aSN1ObjectIdentifierBranch5.branch("5");
        aSN1ObjectIdentifierBranch5.branch("6");
        aSN1ObjectIdentifierBranch5.branch("6");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.5");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.10");
    }
}
