package org.bouncycastle.asn1.bc;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* loaded from: classes4.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bc_exch;
    public static final ASN1ObjectIdentifier bc_ext;
    public static final ASN1ObjectIdentifier bc_pbe;
    public static final ASN1ObjectIdentifier bc_pbe_sha1;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha256;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12;
    public static final ASN1ObjectIdentifier bc_sig;
    public static final ASN1ObjectIdentifier newHope;
    public static final ASN1ObjectIdentifier qTESLA;
    public static final ASN1ObjectIdentifier qTESLA_p_I;
    public static final ASN1ObjectIdentifier qTESLA_p_III;
    public static final ASN1ObjectIdentifier sphincs256;
    public static final ASN1ObjectIdentifier sphincs256_with_BLAKE512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA3_512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA512;
    public static final ASN1ObjectIdentifier xmss;
    public static final ASN1ObjectIdentifier xmss_SHA256;
    public static final ASN1ObjectIdentifier xmss_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_SHA512;
    public static final ASN1ObjectIdentifier xmss_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256ph;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        bc = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier.branch("1");
        bc_pbe = aSN1ObjectIdentifierBranch;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = aSN1ObjectIdentifierBranch.branch("1");
        bc_pbe_sha1 = aSN1ObjectIdentifierBranch2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = aSN1ObjectIdentifierBranch.branch("2.1");
        bc_pbe_sha256 = aSN1ObjectIdentifierBranch3;
        aSN1ObjectIdentifierBranch.branch("2.2");
        aSN1ObjectIdentifierBranch.branch("2.3");
        aSN1ObjectIdentifierBranch.branch("2.4");
        aSN1ObjectIdentifierBranch2.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch4 = aSN1ObjectIdentifierBranch2.branch("2");
        bc_pbe_sha1_pkcs12 = aSN1ObjectIdentifierBranch4;
        aSN1ObjectIdentifierBranch3.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch5 = aSN1ObjectIdentifierBranch3.branch("2");
        bc_pbe_sha256_pkcs12 = aSN1ObjectIdentifierBranch5;
        aSN1ObjectIdentifierBranch4.branch("1.2");
        aSN1ObjectIdentifierBranch4.branch("1.22");
        aSN1ObjectIdentifierBranch4.branch("1.42");
        aSN1ObjectIdentifierBranch5.branch("1.2");
        aSN1ObjectIdentifierBranch5.branch("1.22");
        aSN1ObjectIdentifierBranch5.branch("1.42");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch6 = aSN1ObjectIdentifier.branch("2");
        bc_sig = aSN1ObjectIdentifierBranch6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch7 = aSN1ObjectIdentifierBranch6.branch("1");
        sphincs256 = aSN1ObjectIdentifierBranch7;
        sphincs256_with_BLAKE512 = aSN1ObjectIdentifierBranch7.branch("1");
        sphincs256_with_SHA512 = aSN1ObjectIdentifierBranch7.branch("2");
        sphincs256_with_SHA3_512 = aSN1ObjectIdentifierBranch7.branch("3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch8 = aSN1ObjectIdentifierBranch6.branch("2");
        xmss = aSN1ObjectIdentifierBranch8;
        xmss_SHA256ph = aSN1ObjectIdentifierBranch8.branch("1");
        xmss_SHA512ph = aSN1ObjectIdentifierBranch8.branch("2");
        xmss_SHAKE128ph = aSN1ObjectIdentifierBranch8.branch("3");
        xmss_SHAKE256ph = aSN1ObjectIdentifierBranch8.branch("4");
        xmss_SHA256 = aSN1ObjectIdentifierBranch8.branch("5");
        xmss_SHA512 = aSN1ObjectIdentifierBranch8.branch("6");
        xmss_SHAKE128 = aSN1ObjectIdentifierBranch8.branch("7");
        xmss_SHAKE256 = aSN1ObjectIdentifierBranch8.branch("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch9 = aSN1ObjectIdentifierBranch6.branch("3");
        xmss_mt = aSN1ObjectIdentifierBranch9;
        xmss_mt_SHA256ph = aSN1ObjectIdentifierBranch9.branch("1");
        xmss_mt_SHA512ph = aSN1ObjectIdentifierBranch9.branch("2");
        xmss_mt_SHAKE128ph = aSN1ObjectIdentifierBranch9.branch("3");
        xmss_mt_SHAKE256ph = aSN1ObjectIdentifierBranch9.branch("4");
        xmss_mt_SHA256 = aSN1ObjectIdentifierBranch9.branch("5");
        xmss_mt_SHA512 = aSN1ObjectIdentifierBranch9.branch("6");
        xmss_mt_SHAKE128 = aSN1ObjectIdentifierBranch9.branch("7");
        xmss_mt_SHAKE256 = aSN1ObjectIdentifierBranch9.branch("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch10 = aSN1ObjectIdentifierBranch6.branch("4");
        qTESLA = aSN1ObjectIdentifierBranch10;
        aSN1ObjectIdentifierBranch10.branch("1");
        aSN1ObjectIdentifierBranch10.branch("2");
        aSN1ObjectIdentifierBranch10.branch("3");
        aSN1ObjectIdentifierBranch10.branch("4");
        aSN1ObjectIdentifierBranch10.branch("5");
        qTESLA_p_I = aSN1ObjectIdentifierBranch10.branch("11");
        qTESLA_p_III = aSN1ObjectIdentifierBranch10.branch("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch11 = aSN1ObjectIdentifier.branch("3");
        bc_exch = aSN1ObjectIdentifierBranch11;
        newHope = aSN1ObjectIdentifierBranch11.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch12 = aSN1ObjectIdentifier.branch("4");
        bc_ext = aSN1ObjectIdentifierBranch12;
        aSN1ObjectIdentifierBranch12.branch("1");
    }
}
